name: GitHub Container Registry
on:
    workflow_dispatch:
    push:
        tags:
            - "v*"
        branches:
            - "*"

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    ghcr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=sha,prefix=,suffix=-{{date 'X'}}
                      type=raw,enable=${{ !startsWith(github.ref, 'refs/tags/') }},value=develop
                      type=semver,pattern={{raw}}
            - run: echo "GIT_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV
            - run: echo "GIT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  # Pass github.sha to Docker as GIT_COMMIT & GIT_DATE
                  build-args: |
                    GIT_COMMIT=${{ github.sha }}
                    GIT_DATE=${{ env.GIT_DATE }}
                    GIT_VERSION=${{ env.GIT_VERSION }}
